In [ ]:
# Titan Dataset

In [ ]:
#Import important libraries
import pandas as pd           #loading,analysing,and cleaning
import matplotlib.pyplot as plt   #visualize distribution and outlier identificationn
import numpy as np                 #numerical  calculation

In [ ]:
#load the dataset
df=pd.read_csv("/content/train_titanic.csv")

print("dataset loaded successfully")

dataset loaded successfully

In [ ]:
df.info()         # information of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Gender          object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
print(df.shape)    # no.of rows and column

(891, 12)

In [ ]:
df.head()     #first five rows

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail()                #last five rows

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
#Check missing values

df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#Check percentage of missing values

missing_table = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": df.isnull().sum()/len(df)*100
})

display(missing_table)

                 Missing Values  Missing Percentage
PassengerId                   0            0.000000
Survived                      0            0.000000
Pclass                        0            0.000000
Name                          0            0.000000
Gender                        0            0.000000
Age                           0            0.000000
SibSp                         0            0.000000
Parch                         0            0.000000
Ticket                        0            0.000000
Fare                          0            0.000000
Cabin                       687           77.104377
Embarked                      2            0.224467
Cabin_Available               0            0.000000

In [ ]:
#handle missing values

print("Median Age:", df["Age"].median())      #calculcute the median for missing values

Median Age: 28.0

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())    #fill the missing values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PassengerId      891 non-null    int64
 1   Survived         891 non-null    int64
 2   Pclass           891 non-null    int64
 3   Name             891 non-null    object
 4   Gender           891 non-null    object
 5   Age              891 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Embarked         889 non-null    object
 11  Cabin_Available  891 non-null    int64
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB

In [ ]:
print("Missing Age values:", df["Age"].isnull().sum())

Missing Age values: 0

    Cabin has 687 missing values, approximately 77.10% of the dataset
    Instead of deleting all the rows containing missing Cabin values, preserve the information by creating a new feature
    1 = Cabin information available
    0 = Cabin information missing

    Then remove the original Cabin column because most of its values are missing.

In [ ]:
import pandas as pd

# Load original data
df_raw = pd.read_csv("/content/train_titanic.csv")

# Make a copy for cleaning
df = df_raw.copy()

print("Original shape:", df.shape)
print(df.columns.tolist())

Original shape: (891, 12)
['PassengerId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [ ]:
df["Cabin_Available"] = df["Cabin"].notnull().astype(int)

KeyError: 'Cabin'

In [ ]:
df = df.drop(columns=["Cabin"])

In [ ]:
print(df["Embarked"].value_counts())